name: Deploy Hakyll website to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Cache Docker images.
#        uses: ScribeMD/docker-cache@0.5.0
#        with:
#          key: docker-${{ runner.os }}-${{ hashFiles(paths) }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Bundle
        uses: bundle install
      - name: Build with Hakyll
        uses: stephenswat/hakyll-build-pages@v1.0.7
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
